# Generated by Django 2.2.4 on 2019-09-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species_expert',
            name='badge_pending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='species_expert',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
