# Generated by Django 2.2.4 on 2019-09-16 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190916_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='species_expert',
            name='info_and_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species_expert',
            name='species_colloquial',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
