# Generated by Django 2.2.4 on 2019-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190916_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expert_badge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
