# Generated by Django 2.2.4 on 2019-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_expert_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species_expert',
            name='species_colloquial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
