# Generated by Django 2.2.4 on 2019-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190916_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_curator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
