# Generated by Django 2.2.4 on 2019-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
