# Generated by Django 2.2.5 on 2019-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_curator_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='species_expert',
            name='was_endorsed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
