# Generated by Django 2.2.5 on 2019-10-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_species_expert_was_endorsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='species_expert',
            name='recommended_rejection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
