# Generated by Django 2.2.5 on 2019-10-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_species_expert_recommended_rejection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fws_badge',
            new_name='regulator',
        ),
    ]
