# Generated by Django 2.2.5 on 2019-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191025_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='species_expert',
            name='recommended_removal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
