# Generated by Django 2.2.5 on 2019-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_species_expert_recommended_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_subscribed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
